github:
  project_number: 1
  status_field: PVTSSF_lAHOAGOUg84BSbHizg_9lAw
  status_mapping:
    in-progress: 47fc9ee4
    done: '98236657'
  repo_owner: markiyanm
  repo_name: lite-pos
  project_id: PVT_kwHOAGOUg84BSbHi
